executable = sub_condor.csh

output     = output/output_$(ClusterId)_$(ProcId).out
error      = output/output_$(ClusterId)_$(ProcId).err
log        = output/output_$(ClusterId)_$(ProcId).log

getenv     = True

#environment = "X509_USER_PROXY=$ENV(HOME)/x509up_u61469"

requirements = (OpSysAndVer =?= "CentOS7")

#request_memory = 16000
#request_memory = 24000
request_memory = 32000
#request_memory = 48000

#+JobFlavour = "longlunch"
#+JobFlavour = "workday"
+JobFlavour = "tomorrow"

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT
transfer_output_files = ""

queue arguments from (
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-Excl --apply_exclusive
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-Excl --apply_exclusive
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-PreSel
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-PreSel-Pt1_30-Pt2_20 --min_pt_1=30.0 --min_pt_2=20.0
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-DoubleArm-Pt1_30-Pt2_20 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-PreSel-Rnd-Res20 --random_protons --resample_factor=20 --read_size=50MB
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-PreSel-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-PreSel-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017B.root UL2017B-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel_0 --start=0 --events=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel_1 --start=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20 --min_pt_1=30.0 --min_pt_2=20.0
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --start=0 --events=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --start=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=0 --events=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Rnd-Res20 --random_protons --resample_factor=20 --read_size=50MB
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Rnd-Res20_0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Rnd-Res20_1 --random_protons --resample_factor=20 --read_size=50MB --start=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=6000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_4 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=8000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_5 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=10000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=6000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_4 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=8000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C1.root UL2017C1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_5 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=10000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel
    /eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel_0 --start=0 --events=10000000
    /eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel_1 --start=10000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20 --min_pt_1=30.0 --min_pt_2=20.0
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --start=0 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --start=5000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20_2 --min_pt_1=30.0 --min_pt_2=20.0 --start=10000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20_3 --min_pt_1=30.0 --min_pt_2=20.0 --start=15000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20_4 --min_pt_1=30.0 --min_pt_2=20.0 --start=20000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=0 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=5000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=10000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20_3 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=15000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20_4 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=20000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Rnd-Res20_0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Rnd-Res20_1 --random_protons --resample_factor=20 --read_size=50MB --start=5000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Rnd-Res20_2 --random_protons --resample_factor=20 --read_size=50MB --start=10000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Rnd-Res20_3 --random_protons --resample_factor=20 --read_size=50MB --start=15000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=6000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_4 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=8000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_5 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=10000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_6 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=12000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_7 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=14000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_8 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=16000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_9 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=18000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-PreSel-Pt1_30-Pt2_20-Rnd-Res20_10 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=20000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=6000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_4 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=8000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_5 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=10000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_6 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=12000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_7 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=14000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_8 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=16000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_9 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=18000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017E.root UL2017E-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_10 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2  --random_protons --resample_factor=20 --read_size=50MB --start=20000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-PreSel
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-PreSel-Pt1_30-Pt2_20 --min_pt_1=30.0 --min_pt_2=20.0
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-DoubleArm-Pt1_30-Pt2_20 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-PreSel-Rnd-Res20 --random_protons --resample_factor=20 --read_size=50MB
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-PreSel-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --random_protons --resample_factor=20 --read_size=50MB --start=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F1.root UL2017F1-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-PreSel
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-DoubleArm-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=0 --events=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-DoubleArm-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-PreSel-Rnd-Res20 --random_protons --resample_factor=20 --read_size=50MB
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-PreSel-Rnd-Res20_0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-PreSel-Rnd-Res20_1 --random_protons --resample_factor=20 --read_size=50MB --start=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017C2.root UL2017C2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-PreSel
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-DoubleArm-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=0 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-DoubleArm-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-PreSel-Rnd-Res20 --random_protons --resample_factor=20 --read_size=50MB
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=6000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017D.root UL2017D-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_4 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=8000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-PreSel
    /eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-PreSel_0 --start=0 --events=10000000
    /eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-PreSel_1 --start=10000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=0 --events=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=6000000 --events=6000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=12000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-PreSel-Rnd-Res20_0 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-PreSel-Rnd-Res20_1 --random_protons --resample_factor=20 --read_size=50MB --start=5000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-PreSel-Rnd-Res20_2 --random_protons --resample_factor=20 --read_size=50MB --start=10000000 --events=5000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-PreSel-Rnd-Res20_3 --random_protons --resample_factor=20 --read_size=50MB --start=15000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=6000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_4 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=8000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_5 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=10000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_6 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=12000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_7 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=14000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F2.root UL2017F2-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_8 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=16000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-PreSel
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-DoubleArm-Pt1_30-Pt2_20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=0 --events=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-DoubleArm-Pt1_30-Pt2_20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --start=4000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-PreSel-Rnd-Res20 --random_protons --resample_factor=20 --read_size=50MB
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_0 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=0 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_1 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=2000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_2 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=4000000 --events=2000000
    #/eos/cms/store/group/phys_pps/dilepton/DoubleMuon/UL-MiniAOD-2017/DoubleMuon_UL2017F3.root UL2017F3-DoubleArm-Pt1_30-Pt2_20-Rnd-Res20_3 --min_pt_1=30.0 --min_pt_2=20.0 --apply_doublearm --version=V2 --random_protons --resample_factor=20 --read_size=50MB --start=6000000
)
